name: TowerDefense
author: Nikl
main: me.nikl.towerdefense.Main
version: 0.0.1-Beta
website: nikl.me
softdepend: [Citizens]

commands:
  tdtest:
    description: test td
    usage: /tdtest
    aliases: [tdt]
  towerdefense:
    description: tower defense main command
    usage: /towerdefense
    aliases: [td]
  tdarena:
    description: tower defense arena command
    usage: /tdarena
    aliases: [tda]